### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by kiwinesian** [woonsanko/hippo-on-spring-boot#2]
Hello,

I was able to compile and run locally with no problem.
But it seems like I cant deploy to Heroku?
Maybe you can give a bit of pointer?

Maven home: /usr/local/apache-maven/apache-maven-3.3.9
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

`[FATAL] Non-resolvable parent POM for com.github.woonsanko:hippo-on-spring-boot-spring-boot-deploy:[unknown-version]: Could not find artifact com.github.woonsanko:hippo-on-spring-boot:pom:0.1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 11`

**Comment by woonsanko** [comment]
Hi @stjokro ,

Thanks for testing it on Heroku!
I guess it is because the heroku maven build env is not able to find the snapshot artifacts of the parent and other submodule project other than the spring-boot-deploy submodule since you probably execute the maven command in the spring-boot-deploy submodule.
One possible solution might be to split the spring-boot-deploy module project as a separate independent project that depend on the other modules such as cms and site war modules. If the dependent war modules are available somewhere in other maven repository which is accessible from the heroku maven build env, then the deployment would be successful.

Unfortunately, I don't have a heroku env to access/test right now, but I hope it could help.

Regards,

Woonsan

**Comment by kiwinesian** [comment]
Hello,

Thanks for getting back!
I think I've got further out from here since then. :)

I think I ran into an issue where the slug is too big, 724MB the last time I left it.
Is it suppose to be this big?
It's fairly large for a CMS coming from Drupal and Rails' CMSes.

Just looking for a bit of pointer here.
Would be good to see if I can get this one going! :)

Thanks @woonsanko !

**Comment by woonsanko** [comment]
Closing as it's outdated.
